# Generated by Django 4.0.6 on 2022-08-06 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_usercourses1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCourses1',
        ),
    ]
