# Generated by Django 4.0.6 on 2022-08-05 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Institutes', '0002_role_students_labs_end_time_labs_start_time_and_more'),
        ('ResourceApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('resource', models.CharField(max_length=500)),
                ('units', models.CharField(max_length=500)),
                ('dates', models.CharField(max_length=500)),
                ('start_time', models.CharField(max_length=500)),
                ('end_time', models.CharField(max_length=500)),
                ('labs', models.CharField(max_length=500)),
                ('cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.IntegerField()),
                ('units', models.IntegerField(default=1)),
                ('add_date', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('cost', models.FloatField()),
                ('is_approved', models.IntegerField(default=0)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Institutes.resources')),
            ],
        ),
    ]
