# Generated by Django 4.0.6 on 2022-08-10 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Institutes', '0007_alter_labs_lab_staff'),
        ('ResourceApp', '0003_alter_availability_day_alter_availability_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_slots',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False)),
                ('lab', models.IntegerField(null=True)),
                ('units', models.IntegerField()),
                ('day', models.TextField(null=True)),
                ('date', models.DateField()),
                ('start_time', models.IntegerField()),
                ('end_time', models.IntegerField()),
                ('approved', models.IntegerField(default=0)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Institutes.resources')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tid', models.TextField()),
                ('seller', models.IntegerField()),
                ('resource', models.IntegerField()),
                ('transaction_date', models.DateField(auto_now=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('cost', models.IntegerField()),
                ('units', models.IntegerField()),
                ('status', models.IntegerField(default=0)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Institutes.institutes')),
            ],
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='buyer_institute',
        ),
        migrations.AddField(
            model_name='bill',
            name='buyer_institute',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='seller_institute',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='seller_institute',
            field=models.IntegerField(default=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bill',
            name='cost',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='dates',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='end_time',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='labs',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='resource',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='start_time',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='units',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
