# Generated by Django 4.0.6 on 2022-08-13 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Institutes', '0010_labs_edit_approval_resources_edit_approval'),
        ('ResourceApp', '0004_book_slots_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='workforce',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Institutes.workforce'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='is_approved',
            field=models.IntegerField(default=1),
        ),
    ]
