# Generated by Django 4.0.6 on 2022-08-16 10:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Institutes', '0011_remove_labs_lab_staff_remove_labs_resource_id_and_more'),
        ('ResourceApp', '0005_cart_workforce_alter_cart_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('finalcost', models.FloatField(null=True)),
                ('datetime_of_payment', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_status', models.IntegerField(choices=[(1, 'SUCCESS'), (-1, 'FAILURE'), (0, 'PENDING')], default=0)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=500, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=500, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductInOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ord', models.IntegerField(null=True)),
                ('buyer_institute', models.IntegerField()),
                ('seller_institute', models.IntegerField()),
                ('units', models.IntegerField(default=1)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('cost', models.FloatField()),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Institutes.resources')),
                ('workforce', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Institutes.workforce')),
            ],
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='date',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='status',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_date',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='units',
        ),
        migrations.AddField(
            model_name='transaction',
            name='finalcost',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cost',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='buyer',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Institutes.institutes'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tid',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_items',
            field=models.ManyToManyField(to='ResourceApp.productinorder'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ResourceApp.order'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='order_items',
            field=models.ManyToManyField(to='ResourceApp.productinorder'),
        ),
    ]
