# Generated by Django 4.0.6 on 2022-08-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResourceApp', '0007_alter_transaction_buyer_alter_transaction_tid'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_paid',
            field=models.IntegerField(default=0),
        ),
    ]
