# Generated by Django 4.0.6 on 2022-08-21 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Institutes', '0011_remove_labs_lab_staff_remove_labs_resource_id_and_more'),
        ('ResourceApp', '0009_rename_ord_productinorder_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='visitor',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='order',
            name='institute',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.DO_NOTHING, to='Institutes.institutes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='request_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productinorder',
            name='visitor',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
