export { default as LoginPage } from './LoginPage/LoginPage'
export { default as Dashboard } from './Dashboard/Dashboard'
export { default as ProfilePage } from './ProfilePage/ProfilePage'
export { default as AddNewCollegeAdmin } from './CollegeAdmin/AddNewCollegeAdmin/AddNewCollegeAdmin'
export { default as ChangePassword } from './ChangePassword/ChangePassword'
export { default as STPListPage } from './STPListPage/STPListPage'
export { default as STPDetailsPage } from './STPDetailsPage/STPDetailsPage'
export { default as FeedbackFormPage } from './FeedbackFormPage/FeedbackFormPage'
export { default as ProvideSTFeedback } from './Student/ProvideFeedback/ProvideSTFeedback'
export { default as ProvideSCFeedback } from './Student/ProvideFeedback/ProvideSCFeedback'
export { default as TeacherLeaderboard } from './Leaderboards/TeacherLeaderboards/TeacherLeaderboards'
export { default as CollegeLeaderboard } from './Leaderboards/CollegeLeaderboards/CollegeLeaderboards'
export { default as SuperAdminDashboard } from './SuperAdminDashboard/SuperAdminDashboard'
export { default as CollegeDetailsPage } from './CollegeDetailsPage/CollegeDetailsPage'
export { default as FeedbackDrives } from './FeedbackDrives/FeedbackDrives'
export { default as OnboardingPage } from './OnboardingPage/OnboardingPage'
export { default as TeacherLinking } from './OnboardingPage/TeacherLinking'
export { default as GrievancePortal } from './GrievancePortal/GrievancePortal'
export { default as ParentHomePage } from './ParentHomePage/ParentHomePage'
export { default as ProvidePCFeedback } from './ProvidePCFeedback/ProvidePCFeedback'
export { default as ViewFeedback } from './ViewFeedback/ViewFeedback'


