const categories = [
    'All categories',
    'Company Law, Mrtp, Trai, Sebi, Idrai & Rbi',
    'Arbitration Matters',
    'Compensation Matters',
    'Habeas Corpus Matters',
    'Criminal Matters',
    'Appeal Against Orders Of Statutory Bodies',
    'Family Law Matters',
    'Contempt Of Court Matters',
    'Ordinary Civil Matters',
    'Three Judges Bench Matter',
    'Five Judges Bench Matter',
    'Eleven Judges Bench Matter',
    'Seven Judges Bench Matter',
    'Nine Judges Bench Matter',
    'Appointments Etc., Of Constitutional Functionaries',
    'Statutory Appointments And Appointment Of Other Law Officers',
    'Personal Law Matters',
    'Religious & Charitable Endowments',
    'Mercantile Laws, Commercial Transactions Including Banking',
    'Simple Money & Mortgage Matters Etc.',
    'Matters Relating To Judiciary',
    'Admission To Educational Institutions Other Than Medical & Engineering',
    'Establishment And Recognition Of Educational Institutions',
    'Eviction Under The Public Premises (Eviction) Act',
    'Mines, Minerals And Mining Leases',
    'Land Laws And Agricultural Tenancies',
    'Admirality And Maritime Laws',
    'Matters Relating To Commissions Of Enquiry',
    'Matters Relating To Consumer Protection',
    'Matters Pertaining To Armed Forces & Paramilitary Forces',
    'Admission/Transfer To Engineering And Medical Colleges',
    'ALLOCATION OF 15% ALL INDIA QUOTA IN ADMISSION/TRANSFER TO MEDICAL COLLEGES',
    'MATTERS RELATING TO LEASES, GOVT. CONTRACTS & CONTRACTS BY LOCAL BODIES',
    'State Excise-Trading In Liquor-Privileges, Licences-distilleries Breweries',
    'Reference Under Article 143 Of The Constitution Of India',
    'Reference Under Article 317(1) Of The Constitution Of India',
    'Refernce Under Section 11 Of The Competition Act, 2002.',
    'Reference Under Section 14 Of The Right To Information Act, 2005',
    'Labour Matters',
    'Rent Act Matters',
    'Direct Taxes Matter',
    'Indirect Taxes Matters',
    'Land Acquisition & Requisition Matters',
    'Service Matters',
    'Academic Matters',
    'Letter Petition & Pil Matters',
    'Election Matters'
]

export default categories