# Generated by Django 4.0.6 on 2022-08-02 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institutes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=500, null=True)),
                ('pincode', models.IntegerField(null=True)),
                ('email', models.CharField(max_length=500)),
                ('phone_no', models.IntegerField(null=True)),
                ('role_id', models.IntegerField(default=0)),
                ('accredition', models.FileField(null=True, upload_to='accredition')),
                ('sop', models.FileField(null=True, upload_to='sop')),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Labs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lab_staff', models.CharField(max_length=500)),
                ('resource_id', models.CharField(max_length=500)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Institutes.institutes')),
            ],
        ),
        migrations.CreateModel(
            name='WorkForce',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('position', models.CharField(max_length=500)),
                ('role_id', models.IntegerField()),
                ('status', models.IntegerField(default=0)),
                ('password', models.CharField(max_length=100)),
                ('email_id', models.CharField(max_length=500)),
                ('phone_no', models.IntegerField()),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Institutes.institutes')),
            ],
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('specification', models.CharField(max_length=500)),
                ('subject', models.CharField(max_length=500)),
                ('dimension', models.CharField(max_length=500)),
                ('details', models.CharField(max_length=500)),
                ('quantity', models.IntegerField(default=1)),
                ('cost', models.IntegerField()),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Institutes.labs')),
            ],
        ),
        migrations.AddField(
            model_name='labs',
            name='workforce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Institutes.workforce'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to='images')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Institutes.resources')),
            ],
        ),
    ]
