# Generated by Django 4.0.6 on 2022-08-05 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Institutes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=500)),
                ('photo', models.FileField(upload_to='media/student_images')),
                ('email', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='labs',
            name='end_time',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='labs',
            name='start_time',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='resources',
            name='req_approval',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(upload_to='media/resource_images'),
        ),
        migrations.AlterField(
            model_name='institutes',
            name='accredition',
            field=models.FileField(null=True, upload_to='media/accredition'),
        ),
        migrations.AlterField(
            model_name='institutes',
            name='sop',
            field=models.FileField(null=True, upload_to='media/sop'),
        ),
        migrations.AlterField(
            model_name='labs',
            name='lab_staff',
            field=models.CharField(default='<django.db.models.fields.AutoField>', max_length=500),
        ),
        migrations.AlterField(
            model_name='labs',
            name='resource_id',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='labs',
            name='workforce',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Institutes.workforce'),
        ),
        migrations.CreateModel(
            name='Grievence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.FloatField()),
                ('review', models.TextField()),
                ('response', models.TextField(null=True)),
                ('review_time', models.DateTimeField()),
                ('response_time', models.DateTimeField(null=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Institutes.resources')),
            ],
        ),
    ]
