# Generated by Django 4.0.6 on 2022-08-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institutes', '0002_role_students_labs_end_time_labs_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutes',
            name='auth_token',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='workforce',
            name='auth_token',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
