# Generated by Django 4.0.6 on 2022-08-06 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Institutes', '0003_institutes_auth_token_workforce_auth_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='institute_id',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='Institutes.institutes'),
        ),
    ]
