# Generated by Django 4.0.6 on 2022-08-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institutes', '0004_students_institute_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutes',
            name='university',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='workforce',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='workforce',
            name='phone_no',
            field=models.IntegerField(null=True),
        ),
    ]
