# Generated by Django 4.0.6 on 2022-08-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institutes', '0005_alter_institutes_university_alter_workforce_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labs',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='labs',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
