# Generated by Django 4.0.6 on 2022-08-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institutes', '0006_labs_name_labs_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labs',
            name='lab_staff',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
