# Generated by Django 4.0.6 on 2022-08-10 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Institutes', '0007_alter_labs_lab_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edit_lab',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500, null=True)),
                ('lab_staff', models.CharField(max_length=500, null=True)),
                ('resource_id', models.CharField(max_length=500, null=True)),
                ('start_time', models.CharField(max_length=500, null=True)),
                ('end_time', models.CharField(max_length=500, null=True)),
                ('edit_status', models.IntegerField(default=0)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Institutes.institutes')),
                ('workforce', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Institutes.workforce')),
            ],
        ),
    ]
