# Generated by Django 4.0.6 on 2022-08-11 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Institutes', '0008_edit_lab'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Edit_lab',
        ),
    ]
