# Generated by Django 4.0.6 on 2022-08-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institutes', '0009_delete_edit_lab'),
    ]

    operations = [
        migrations.AddField(
            model_name='labs',
            name='edit_approval',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='resources',
            name='edit_approval',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
