# Generated by Django 4.0.6 on 2022-08-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institutes', '0010_labs_edit_approval_resources_edit_approval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labs',
            name='lab_staff',
        ),
        migrations.RemoveField(
            model_name='labs',
            name='resource_id',
        ),
        migrations.AddField(
            model_name='institutes',
            name='account_no',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='institutes',
            name='registeration_no',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='resources',
            name='is_approved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resources',
            name='mrp',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='resources',
            name='under_maintenance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workforce',
            name='idcard',
            field=models.FileField(null=True, upload_to='media/idcards'),
        ),
    ]
