# Generated by Django 4.1 on 2022-08-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institutes', '0011_remove_labs_lab_staff_remove_labs_resource_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=500)),
                ('role_id', models.IntegerField()),
                ('institute', models.CharField(max_length=500)),
            ],
        ),
    ]
