# Generated by Django 4.1 on 2022-08-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institutes', '0012_usser'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='is_software',
            field=models.IntegerField(default=0),
        ),
    ]
