# Generated by Django 4.1 on 2022-08-26 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Institutes', '0012_usser'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPlan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField()),
                ('plan_id', models.IntegerField()),
                ('is_active', models.BooleanField()),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('cost', models.FloatField()),
                ('resource_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Institutes.resources')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Institutes.workforce')),
            ],
        ),
    ]
